# Generated by Django 5.1 on 2024-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(blank=True, max_length=120, null=True)),
                ('adresa', models.CharField(blank=True, max_length=120, null=True)),
                ('fotografija', models.ImageField(upload_to='skupstine/')),
                ('opis', models.TextField(blank=True, null=True)),
                ('attenders', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
