# Generated by Django 5.1 on 2024-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesto',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
