# Generated by Django 5.1 on 2024-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape', '0002_mesto_lat_mesto_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesto',
            name='prodata',
            field=models.BooleanField(default=True),
        ),
    ]
