# Generated by Django 5.1 on 2024-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape', '0003_mesto_prodata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesto',
            name='prodata',
        ),
        migrations.AddField(
            model_name='mesto',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
