# Generated by Django 5.1 on 2024-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape', '0004_remove_mesto_prodata_mesto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesto',
            name='fotografija',
            field=models.ImageField(null=True, upload_to='skupstine/'),
        ),
    ]
