# Generated by Django 5.1 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape', '0005_alter_mesto_fotografija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesto',
            name='fotografija',
            field=models.ImageField(blank=True, null=True, upload_to='skupstine/'),
        ),
    ]
