# Generated by Django 5.1 on 2024-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_image_blogpost_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/sluzbe/'),
        ),
    ]
