# Generated by Django 5.1 on 2024-08-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpost_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-title', '-publish_date', '-updated', '-timestamp']},
        ),
    ]
