# Generated by Django 5.1 on 2024-08-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_pojanjapost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojanjapost',
            options={'ordering': ['album', 'title']},
        ),
    ]
