# Generated by Django 5.1 on 2024-08-28 14:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_folder_pojanjapost_artist_pojanjapost_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='audio',
            field=models.FileField(blank=True, null='',  upload_to='audio/sluzbe/'),
        ),
        migrations.AlterField(
            model_name='pojanjapost',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/pojanja/'),
        ),
    ]
