# Generated by Django 5.1 on 2024-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogpost_audio_alter_pojanjapost_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/sluzbe/'),
        ),
        migrations.AlterField(
            model_name='pojanjapost',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/pojanja/'),
        ),
    ]
