# Generated by Django 5.1 on 2024-08-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_blogpost_audio_alter_pojanjapost_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderSluzbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sluzbe', to='blog.foldersluzbe'),
        ),
    ]
