# Generated by Django 5.1 on 2024-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_foldersluzbe_blogpost_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojanjapost',
            name='language',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
