# Generated by Django 5.1 on 2024-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_pojanjapost_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='language',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
