# Generated by Django 5.1 on 2024-09-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_folder_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojanjapost',
            name='language',
        ),
    ]
