# Generated by Django 5.1 on 2024-09-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knjige', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knjiga',
            old_name='content',
            new_name='Opis',
        ),
    ]
