# Generated by Django 5.1 on 2024-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjige', '0002_rename_content_knjiga_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='knjiga',
            field=models.FileField(blank=True, null='', upload_to='files/knjige/'),
        ),
    ]
