# Generated by Django 5.1 on 2024-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjige', '0003_alter_knjiga_knjiga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knjiga',
            old_name='Opis',
            new_name='opis',
        ),
        migrations.AddField(
            model_name='knjiga',
            name='where_to_buy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='knjiga',
            name='where_to_buy_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
