# Generated by Django 5.1 on 2024-09-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knjige', '0004_rename_opis_knjiga_opis_knjiga_where_to_buy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knjiga',
            name='where_to_buy',
        ),
    ]
