# Generated by Django 5.1 on 2024-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjige', '0005_remove_knjiga_where_to_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='broj_telefona_porudzbine',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='knjiga',
            name='kontakt_za_porudzbine',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
