# Generated by Django 5.1 on 2024-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojanica',
            name='godina_izdanja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
