# Generated by Django 5.1 on 2024-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0002_pojanica_godina_izdanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojanje',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/citanje/'),
        ),
    ]
