# Generated by Django 5.1 on 2024-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0003_pojanje_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapojanja',
            name='broj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pojanje',
            name='broj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
