# Generated by Django 5.1 on 2024-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0004_alter_listapojanja_broj_alter_pojanje_broj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojanje',
            name='skracenica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
