# Generated by Django 5.1 on 2024-10-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0005_pojanje_skracenica'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaraPojanicaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('izdanje', models.CharField(blank=True, max_length=255, null=True)),
                ('godina_izdanja', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaraPojanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('file', models.FileField(blank=True, null='', upload_to='files/pojanice/')),
                ('pojanje', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='pojanice.starapojanicafolder')),
            ],
        ),
    ]
