# Generated by Django 5.1 on 2024-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojanice', '0006_starapojanicafolder_starapojanica'),
    ]

    operations = [
        migrations.AddField(
            model_name='starapojanicafolder',
            name='jezik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
