# Generated by Django 5.1 on 2024-08-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starizavetglave',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glave', to='biblija.starizavetknjige'),
        ),
        migrations.AlterField(
            model_name='starizavettext',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='biblija.starizavetglave'),
        ),
    ]
