# Generated by Django 5.1 on 2024-08-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0002_alter_starizavetglave_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starizavettext',
            name='folder',
        ),
        migrations.AlterField(
            model_name='starizavettext',
            name='glava',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='biblija.starizavetglave'),
        ),
    ]
