# Generated by Django 5.1 on 2024-08-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0003_remove_starizavettext_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starizavettext',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='biblija.starizavetglave'),
        ),
        migrations.AlterField(
            model_name='starizavettext',
            name='glava',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
