# Generated by Django 5.1 on 2024-08-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0005_remove_starizavettext_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starizavetglave',
            name='folder',
        ),
        migrations.AddField(
            model_name='starizavetglave',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='starizavetglave',
            name='knjiga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='glave', to='biblija.starizavetknjige'),
        ),
    ]
