# Generated by Django 5.1 on 2024-08-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0006_remove_starizavetglave_folder_starizavetglave_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoviZavetKnjige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('broj_glava', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoviZavetGlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('knjiga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='glave', to='biblija.novizavetknjige')),
            ],
        ),
        migrations.CreateModel(
            name='NoviZavetText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('glava', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='biblija.novizavetglave')),
            ],
        ),
    ]
