# Generated by Django 5.1 on 2024-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0007_novizavetknjige_novizavetglave_novizavettext'),
    ]

    operations = [
        migrations.AddField(
            model_name='novizavettext',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/citanje/'),
        ),
    ]
