# Generated by Django 5.1 on 2024-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblija', '0008_novizavettext_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='starizavettext',
            name='audio',
            field=models.FileField(blank=True, null='', upload_to='audio/citanje/'),
        ),
    ]
